# Generated by Django 3.2 on 2024-02-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240130_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='appointment',
            field=models.BooleanField(default=False),
        ),
    ]
