# Generated by Django 3.2 on 2024-02-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_medical_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_Name', models.CharField(default='', max_length=255)),
                ('District', models.CharField(default='', max_length=255)),
                ('CityTown', models.CharField(default='', max_length=255)),
                ('Pincode', models.IntegerField()),
                ('Address', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
    ]
