# Generated by Django 3.2 on 2024-02-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240203_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='Pincode',
            field=models.CharField(default='', max_length=255),
        ),
    ]
