# Generated by Django 3.2 on 2024-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240205_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medical_profile',
            field=models.BooleanField(default=False),
        ),
    ]
