# Generated by Django 3.2 on 2024-02-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_medical_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood_high',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_low',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medications',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
