# Generated by Django 3.2 on 2024-02-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_weightrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bmi',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
