# Generated by Django 3.2 on 2024-02-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightrecord',
            name='note',
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='sleep',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
