# Generated by Django 3.2 on 2024-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20240210_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrecord',
            name='sleep',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
