# Generated by Django 3.2 on 2024-02-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_weightrecord_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightrecord',
            name='blood_high',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='blood_low',
            field=models.IntegerField(null=True),
        ),
    ]
