# Generated by Django 3.2 on 2024-02-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20240210_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='blood_high',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='blood_low',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='bmi',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
