# Generated by Django 3.2 on 2024-02-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20240214_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical',
            name='gender',
        ),
    ]
