# Generated by Django 3.2 on 2024-02-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_medical_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='medicine2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
