# Generated by Django 3.2 on 2024-03-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_medical_medicine2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='Password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
