# Generated by Django 3.2 on 2024-03-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_hospitals_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=255)),
                ('Name', models.CharField(default='', max_length=255)),
                ('Specification', models.CharField(default='', max_length=255)),
                ('Password', models.CharField(default='', max_length=255)),
                ('Degree', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
